"""Filesystem storage for spec artifacts.

Layout inside the user's project::

    .coderrr/
    ├── specs/            <- committed; project knowledge, reviewable in PRs
    │   └── 001-add-auth/
    │       ├── requirements.md
    │       ├── design.md
    │       └── tasks.md
    ├── cache/            <- gitignored
    └── session/          <- gitignored

The generated ``.coderrr/.gitignore`` keeps transient state out of version
control while letting specs be committed. v1 wrote conversation history into the
same directory it told git to stage, which is how chat logs ended up in commits.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from coderrr.spec.models import Spec, Task, TaskStatus
from coderrr.spec.parser import parse_tasks, render_tasks

CODERRR_DIR = ".coderrr"
SPECS_DIR = "specs"

GITIGNORE_BODY = """\
# Generated by Coderrr. Transient state stays local; specs are project
# knowledge and are meant to be committed.
cache/
session/
!specs/
"""

_SLUG_RE = re.compile(r"[^a-z0-9]+")
_SPEC_DIR_RE = re.compile(r"^(?P<number>\d{3})-(?P<slug>.+)$")

REQUIREMENTS_TEMPLATE = """\
# Requirements: {title}

## Goal

{goal}

## User Stories

- As a user, I want ..., so that ...

## Acceptance Criteria

- [ ] AC1: ...

## Out of Scope

- ...
"""

DESIGN_TEMPLATE = """\
# Design: {title}

## Approach

...

## Components

...

## Data Flow

...

## Decisions

| Decision | Choice | Rationale |
| --- | --- | --- |
| ... | ... | ... |

## Risks

- ...
"""


def slugify(text: str, *, max_length: int = 40) -> str:
    slug = _SLUG_RE.sub("-", text.strip().lower()).strip("-")
    if len(slug) > max_length:
        slug = slug[:max_length].rstrip("-")
    return slug or "spec"


@dataclass(frozen=True)
class SpecRef:
    """A spec's identity on disk."""

    number: int
    slug: str
    path: Path

    @property
    def name(self) -> str:
        return f"{self.number:03d}-{self.slug}"


class SpecStore:
    """CRUD over ``.coderrr/specs/``."""

    def __init__(self, workspace: Path) -> None:
        self.workspace = workspace
        self.root = workspace / CODERRR_DIR
        self.specs_root = self.root / SPECS_DIR

    # -- setup -----------------------------------------------------------

    def ensure_layout(self) -> None:
        """Create the directory tree and the gitignore that protects it."""
        self.specs_root.mkdir(parents=True, exist_ok=True)
        (self.root / "cache").mkdir(exist_ok=True)
        (self.root / "session").mkdir(exist_ok=True)

        gitignore = self.root / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(GITIGNORE_BODY, encoding="utf-8")

    # -- listing ---------------------------------------------------------

    def list_refs(self) -> list[SpecRef]:
        if not self.specs_root.exists():
            return []
        refs: list[SpecRef] = []
        for entry in sorted(self.specs_root.iterdir()):
            if not entry.is_dir():
                continue
            if match := _SPEC_DIR_RE.match(entry.name):
                refs.append(
                    SpecRef(
                        number=int(match.group("number")),
                        slug=match.group("slug"),
                        path=entry,
                    )
                )
        return refs

    def next_number(self) -> int:
        refs = self.list_refs()
        return max((r.number for r in refs), default=0) + 1

    def find(self, identifier: str) -> SpecRef | None:
        """Resolve a spec by directory name, slug, or zero-padded number."""
        refs = self.list_refs()
        for ref in refs:
            if identifier in (ref.name, ref.slug, f"{ref.number:03d}", str(ref.number)):
                return ref
        return None

    def latest(self) -> SpecRef | None:
        refs = self.list_refs()
        return refs[-1] if refs else None

    # -- create / load / save --------------------------------------------

    def create(self, title: str, *, goal: str = "") -> SpecRef:
        self.ensure_layout()
        ref = SpecRef(
            number=self.next_number(),
            slug=slugify(title),
            path=Path(),
        )
        directory = self.specs_root / f"{ref.number:03d}-{ref.slug}"
        directory.mkdir(parents=True, exist_ok=True)
        ref = SpecRef(number=ref.number, slug=ref.slug, path=directory)

        (directory / "requirements.md").write_text(
            REQUIREMENTS_TEMPLATE.format(title=title, goal=goal or "..."),
            encoding="utf-8",
        )
        (directory / "design.md").write_text(DESIGN_TEMPLATE.format(title=title), encoding="utf-8")
        (directory / "tasks.md").write_text(render_tasks(title, []), encoding="utf-8")
        return ref

    def load(self, ref: SpecRef) -> Spec:
        requirements = self._read(ref.path / "requirements.md")
        design = self._read(ref.path / "design.md")
        tasks_md = self._read(ref.path / "tasks.md")
        title, tasks = parse_tasks(tasks_md)
        return Spec(
            slug=ref.name,
            title=title or ref.slug.replace("-", " "),
            requirements=requirements,
            design=design,
            tasks=tasks,
        )

    def write_document(self, ref: SpecRef, document: str, content: str) -> Path:
        """Write ``requirements``, ``design`` or ``tasks`` for a spec."""
        if document not in {"requirements", "design", "tasks"}:
            raise ValueError(
                f"Unknown spec document '{document}'. Expected one of: requirements, design, tasks."
            )
        ref.path.mkdir(parents=True, exist_ok=True)
        target = ref.path / f"{document}.md"
        target.write_text(content, encoding="utf-8")
        return target

    def save_tasks(self, ref: SpecRef, spec: Spec) -> Path:
        return self.write_document(ref, "tasks", render_tasks(spec.title, spec.tasks))

    def update_task(
        self,
        ref: SpecRef,
        task_id: str,
        *,
        status: TaskStatus | None = None,
        notes: str | None = None,
    ) -> Task:
        spec = self.load(ref)
        task = spec.task(task_id)
        if task is None:
            known = ", ".join(t.id for t in spec.tasks) or "none"
            raise KeyError(f"No task '{task_id}' in {ref.name}. Known tasks: {known}")
        if status is not None:
            task.status = status
        if notes is not None:
            task.notes = notes
        self.save_tasks(ref, spec)
        return task

    @staticmethod
    def _read(path: Path) -> str:
        try:
            return path.read_text(encoding="utf-8")
        except OSError:
            return ""
